#!/bin/bash
set -e -x
brew tap neovim/neovim
brew tap caskroom/cask
brew tap caskroom/fonts
brew update
brew install \
  git \
  neovim \
  postgresql \
  node \
  python2 \
  python3 \
  tmux \
  reattach-to-user-namespace \
  parallel \
  redis \
  graphicsmagick \
  tig \
  the_silver_searcher \
  heroku \
  htop \
  colordiff \
  ripgrep
brew cask install \
  slack \
  skype \
  spectacle \
  1password \
  alfred \
  iterm2 \
  google-chrome \
  dropbox \
  dash \
  ngrok \
  caffeine \
  rescuetime
brew cask install \
  font-meslo-nerd-font \
  font-hack-nerd-font \
  font-ubuntu-nerd-font-mono \
  font-firacode-nerd-font

brew services start redis
brew services start postgresql

pip install \
  neovim \
  powerline-status \
  psutil

npm install -g pm2

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install node
nvm install --lts
nvm use --lts
npm install -g yarn lerna eslint_d
nvm use node
npm install -g yarn lerna eslint_d
nvm alias default node


# PLv8 stuff:
##pip install pgxnclient
##brew install homebrew/versions/v8-315
##LIBRARY_PATH="/usr/local/opt/v8-315/lib" CPATH="/usr/local/opt/v8-315/include" pgxnclient install plv8=1.4.3

brew install v8
curl -LO https://github.com/plv8/plv8/archive/v2.1.0.tar.gz
tar -xf v2.1.0.tar.gz
cd plv8-2.1.0
make static
make install

echo
echo
echo "########################################"
echo "########################################"
echo "########################################"
echo "########################################"
echo
echo

pm2 startup
