#!/bin/bash
export PATH="/usr/local/bin:/usr/local/share/npm/bin:$PATH"

alias vim="mvim -v"
export EDITOR="vim"
alias TextWrangler="open -a TextWrangler"
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '
alias MacVim="open -a MacVim.app"
alias vim='mvim -v'

# jemjie's s3cmd
alias s3cmd_jemjie="s3cmd --config=/Users/benjiegillam/.s3cfg_jemjie --bucket-location=EU"
alias js3cmd=s3cmd_jemjie
alias chrome="open -a 'Google Chrome'"

# tig pull - for doing a git pull and then having `tig` show you the changes.
alias 'tigpull'='RANGE=$(git -c color.ui=always pull | tee /dev/tty | grep "^Updating .*\.\." | sed "s/Updating //"); if [ "$RANGE" != "" ]; then tig $RANGE; fi'

# Ruby
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
