#!/bin/bash
export PATH="/usr/local/sbin:/usr/local/bin:/usr/local/share/npm/bin:$PATH:/Users/benjiegillam/.apportable/SDK/bin"
export ANDROID_HOME=/usr/local/opt/android-sdk
export NEWRELIC_AGENT_ENABLED=false

alias vim="mvim -v"
export EDITOR="vim"
alias TextWrangler="open -a TextWrangler"
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias go='git checkout '
#alias gr='git reset '
alias gt='git tag '
alias gr='git rebase '
alias gri='git rebase -i '
alias gk='gitk --all&'
alias gx='gitx --all'
alias ghurl='git ghurl'
alias gpu='git push -u origin $(git rev-parse --abbrev-ref HEAD)'
alias gpupr='git push -u origin $(git rev-parse --abbrev-ref HEAD) && open $(ghurl)/compare/$(git rev-parse --abbrev-ref HEAD)?expand=1'

if [ "$SHELL" == "$(which zsh)" ]; then
  compdef _git go="git-checkout"
  compdef _git ga="git-add"
  compdef _git gr="git-rebase"
  alias __git-checkout_main=_git_checkout
  alias __git-add_main=_git_add
  alias __git-rebase_main=_git_rebase
fi

alias got='git '
alias get='git '
alias MacVim="open -a MacVim.app"
alias vim='mvim -v'

alias z='zeus'
alias zr='zeus rspec'
alias zpr='zeus parallel_rspec'
alias migrate='zeus rake db:migrate'
alias rollback='zeus rake db:rollback'

alias rshl='pkill -f "devserver.coffee hotloader"'
alias ghpr='git pull-request'

function fixupstream {
  BRANCH="$(git symbolic-ref HEAD)" || return 1
  BRANCH=${BRANCH##refs/heads/}
  git branch --set-upstream-to="origin/${BRANCH}" "${BRANCH}"
}

#function gpu {
#  BRANCH="$(git symbolic-ref HEAD)" || return 1
#  BRANCH=${BRANCH##refs/heads/}
#  git push -u origin "${BRANCH}"
#}

function gpr {
  # `git pull --rebase` with automatic stash and attempt to restore
  MOD_COUNT=$(git status --porcelain --untracked-files=no | wc -l)
  if [ $MOD_COUNT -gt 0 ]; then
    if git stash save "git pull --rebase stash" && git pull --rebase && git stash apply && git stash drop; then
      echo "Success";
    else
      echo
      echo
      echo "WARNING: Something failed! Read the above!"
    fi
  else
    git pull --rebase
  fi
}

# jemjie's s3cmd
alias s3cmd_jemjie="s3cmd --config=/Users/benjiegillam/.s3cfg_jemjie --bucket-location=EU"
alias js3cmd=s3cmd_jemjie
alias chrome="open -a 'Google Chrome'"

# tig pull - for doing a git pull and then having `tig` show you the changes.
alias 'tigpull'='RANGE=$(git -c color.ui=always pull | tee /dev/tty | grep "^Updating .*\.\." | sed "s/Updating //"); if [ "$RANGE" != "" ]; then tig $RANGE; fi'

# Selenium browser testing
alias 'selenium-server-standalone'='java -jar /usr/local/opt/selenium-server-standalone/selenium-server-standalone-2.*.jar -p 4444'

# Mocha
alias 'mocha-bg'='./node_modules/.bin/mocha --reporter spec --compilers coffee:coffee-script'

# I want to be able to open more than a couple files, OSX, please
# I needed to increase this even more because of all the file watching I do
ulimit -n 10240

# Ruby
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Colours
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# hub / GitHub
eval "$(hub alias -s)"

# npm autocomplete
. <(npm completion)
