#!/bin/bash
alias vim="mvim -v"
export EDITOR="vim"
alias TextWrangler="open -a TextWrangler"
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '
alias MacVim="open -a MacVim.app"

alias chrome="open -a 'Google Chrome'"
